config/routes.rb
Rails.application.routes.draw do

  get 'documents/index'
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'telephone_directory/index'

  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'homes/show', to:"homes#show"
  get 'homes/index', to:"homes#index"
  get 'homes/tool', to:"homes#tool"
  get 'homes/search', to:"homes#search"

  # utility
  get 'homes/dateConverter', to:"homes#dateConverter"
  get 'homes/currency', to:"homes#currency"
  get 'homes/freeConverter', to:"homes#freeConverter"
  get 'homes/goldSilver', to:"homes#goldSilver"
  get 'homes/nepaliCalendar', to:"homes#nepaliCalendar"
  get 'homes/panchang', to:"homes#panchang"
  get 'homes/rashifall', to:"homes#rashifall"
  get 'homes/unicode', to:"homes#unicode"
  get 'homes/weather', to:"homes#weather"
  get 'homes/document', to:"homes#document"

  get 'set_mylanguage/np', to:"set_mylanguage#np"
  get 'set_mylanguage/en', to:"set_mylanguage#en"

  get 'realestates/rent', to:"realestates#rent"
  get 'realestates/sell', to:"realestates#sell"

  get 'aboutus/index', to:"aboutus#index"
  get 'contactus/index', to: "contactus#index"
  get 'contactus/new', to: "contactus#new"

   get 'listings/show', to:"listings#show"
   get 'listings/new', to:"listings#new"
   post 'listings/new', to:"listings#new"
   post 'listings/create', to:"listings#create"
   get 'notes/notes_show'


   resources :bus_departures, only: [:index]
   resources :models, only: [:index, :show]
   resources :events,only: [:index,:new,:create]
   resources :marketplaces,:professionals
   resources :notes, only: [:index]
   resources :gamifications, only: [:index]
   resources :statistics, only: [:index]
   resources :projects, only: [:index,:show]
   resources :tags, only: [:index]

   get 'notes/notes_index'
   get 'notes/notes_download'
   get 'notes/syllabus_index'
   get 'gamifications/reward'

   
   #routes for statistics
  
   get 'statistics/bhimdatt_index'
   get 'statistics/punarbas_index'
   get 'statistics/krishnapur_index'
   get 'statistics/mahakali_index'
   get 'statistics/suklaphata_index'
   get 'statistics/belauri_index'
   get 'statistics/betkot_index'
   get 'statistics/laljhadi_index'
   get 'statistics/beldadi_index'

   #routes for arcy#
   resources :donors
   resources :vacancies
   resources :pet_adoptions
   resources :documents
   resources :sections

   #################



   get 'listings/sucess', to: "listings#sucess"

   resources :agents, only: [:index]


  root 'homes#index'
  resources :realestates
  resources :tourists
 

  resources :listings do
      resources :reviews
  end
  resources :projects do
      resources :donations
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  mount SimpleDiscussion::Engine => "/forum"

  #mnr forum
  resources :poll_votes
  resources :posts do
    resources :post_comments
    member do
      put "like" => "posts#upvote"
      put "dislike" => "posts#downvote"
      put "follow" => "posts#follow"
      put "unfollow" => "posts#unfollow"
    end
  end

  mount ActionCable.server => '/cable'

  #for API
  mount API::Base, at: "/"

end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :subject
  mount_uploader :note_pdf, NoteUploader

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	def index
		@universities = University.includes(:university_departments)
		@semesters = UniversitySemester.order(:name).includes(:subjects)
		@subjects = Subject.all
	end

	def notes_show
		@subject=Subject.find(params[:id])
	end

	def notes_index
		headers = {'Authorization':'token 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'} 
		url = "https://api.github.com/repos/Naren404/MNRYP_notes/contents/#{params[:uni]}/#{params[:dept]}/#{params[:sub_dept]}/#{params[:sem]}/#{params[:sub]}"
		response = HTTParty.get(url,headers: headers)

		result = response.parsed_response 

		@chapters = result
	end

	

	def notes_download
		require "open-uri"
		url=params[:download_url]
    	send_file(URI.open(url),
    	:filename => params[:filename],
      	:type => 'application/pdf/docx/html/htm/doc',
      	:disposition => 'attachment')  
	end

	def syllabus_index
		headers = {'Authorization':'token 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'} 
		url = "https://api.github.com/repos/Naren404/MNRYP_notes/contents/#{params[:uni]}/#{params[:dept]}/#{params[:sub_dept]}/#{params[:sem]}/#{params[:sub]}/syllabus"
		response = HTTParty.get(url,headers: headers)

		result = response.parsed_response 

		@syllabus  = result
	end 
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/index.html.erb
<% content_for :title, "Notes" %>
<%= render 'Homepage/navmenu' %>
<div class="row scrolling-wrapper row flex-row ">
<% @universities.each do |university| %>
	<div class="col-md-4">
		<div class="tree ">
		    <ul>
		    	<!-------universities------------->
		        <li>
					<span class="px-2">
						<a 
						style="color:#000;" 
						data-toggle="collapse" 
						href="#<%= university.name.to_s.delete(" ") %>departments" 
						aria-expanded="true" 
						aria-controls="<%= university.name.to_s.delete(" ") %>departments">
							<i class="collapsed"><i class="fas fa-folder"></i></i>
							<i class="expanded"><i class="far fa-folder-open"></i></i>
							<%= university.name %>
						</a>
					</span>
					<!-------------departments------------->
					<div id="<%= university.name.to_s.delete(" ") %>departments" class="collapse show">
						<ul>
							<% university.university_departments.each do |department| %>
								<li>
									<span class="text-uppercase responsive-text px-2">
									  <a 
									    style="color:#000;"
									    data-toggle="collapse"
									    href="#<%= university.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %>subdepartments" 
									    aria-expanded="false" 
									    aria-controls="<%= university.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %>subdepartments">

										    <i class="collapsed"><i class="fas fa-folder"></i></i>
										    <i class="expanded"><i class="far fa-folder-open"></i></i>
										    <%= department.name %>
									  </a>
									</span>
									<!------------sub departments---------------------------->
									<div id="<%= university.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %>subdepartments" class="collapse">
										<ul>
											<% department.sub_departments.each do |sub_department| %>
												<li>
													<span class="text-uppercase responsive-text px-2">
														<a 
														style="color:#000;" 
														data-toggle="collapse" 
														href="#<%= university.name.to_s.delete(" ") %><%= sub_department.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %>semesters" 
														aria-expanded="false" 
														aria-controls="<%= university.name.to_s.delete(" ") %><%= sub_department.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %>semesters">

															<i class="collapsed"><i class="fas fa-folder"></i></i>
															<i class="expanded"><i class="far fa-folder-open"></i></i>
															<%= sub_department.name %>

														</a>
													</span>
													<!-----------semesters------------------>
													<div id="<%= university.name.to_s.delete(" ") %><%= sub_department.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %>semesters" class="collapse">
														<ul>
															<% @semesters.each do |semester| %>
																<li>
																	<span class="responsive-text px-2">
																		<a 
																		style="color:#000;" 
																		data-toggle="collapse" 
																		href="#<%= university.name.to_s.delete(" ") %><%= sub_department.name.to_s.delete(" ") %><%= department.name %><%= semester.name.to_s.delete(" ") %>subjects" 
																		aria-expanded="false" 
																		aria-controls="<%= university.name.to_s.delete(" ") %><%= sub_department.name.to_s.delete(" ") %><%= department.name %><%= semester.name.to_s.delete(" ") %>subjects">

																			<i class="collapsed"><i class="fas fa-folder"></i></i>
																			<i class="expanded"><i class="far fa-folder-open"></i></i>
																			<%= semester.name %>

																		</a>
																	</span>
																	<!----------------semesters----------------------------->
																	<div id="<%= university.name.to_s.delete(" ") %><%= sub_department.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %><%= semester.name.to_s.delete(" ") %>subjects" class="collapse">
																		<ul>
																			<% semester.subjects.where("sub_department_id=?",sub_department.id).each do  |subject| %>
																				<li>
																					<span class="responsive-text px-1">
																					<a 
																					style="color:#000;" 
																					data-toggle="collapse" 
																					href="#<%= university.name.to_s.delete(" ") %><%= sub_department.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %><%= subject.name.to_s.delete(" ") %>" 
																					aria-expanded="false" 
																					aria-controls="<%= university.name.to_s.delete(" ") %><%= sub_department.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %><%= subject.name.to_s.delete(" ") %>">

																						<i class="collapsed"><i class="fas fa-folder"></i></i>
																						<i class="expanded"><i class="far fa-folder-open"></i></i>
																						<%= subject.name %>

																					</a>
																					</span>
																					<!-----------------notes-------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
																					<div id="<%= university.name.to_s.delete(" ") %><%= sub_department.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %><%= subject.name.to_s.delete(" ") %>" class="collapse">
																						<ul>
																							<li>
																								<%= link_to notes_notes_show_path(), style:"color:#000; text-decoration:none;" do %>
																									<span class="responsive-text px-1"><i class="collapsed"><i class="fas fa-folder"></i></i> Notes</span>
																								<% end %>
																							</li>
																							<li>
																							<%= link_to notes_syllabus_index_path(uni:"#{university.name.to_s.delete(" ")}",dept:"#{department.name.to_s.delete(" ")}",sub_dept:"#{sub_department.name.to_s.delete(" ")}",sem:"#{semester.name.to_s.delete(" ")}",sub:"#{subject.name.to_s.delete(" ")}"), syllabus:"syllabus", style:"color:#000; text-decoration:none;" do %>
																									<span class="responsive-text px-1"><i class="collapsed"><i class="fas fa-folder"></i></i> Syllabus</span>
																								<% end %>
																							</li>
																							<li><span class="responsive-text px-1"><i class="collapsed"><i class="fas fa-folder"></i></i> Question Papers</span></li>
																							<li><span class="responsive-text px-1"><i class="collapsed"><i class="fas fa-folder"></i></i> Case Studies</span></li>
																						</ul>
																					</div>
																					<!---------------------syllabus------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
																				
																				</li> 
																			<% end %>
																		</ul>
																	</div>
		                                    
																</li>
															<% end %>
														</ul>
													</div>
												</li>
											<% end %>
										</ul>
									</div>
								</li>
							<% end %>
						</ul>
					</div>
		        </li>
		    </ul>
		</div>
	</div>
<% end %>
</div>
<style type="text/css">.scrolling-wrapper{
	overflow-x: auto;
}</style>

app/views/notes/notes_index.html.erb
<% content_for :title, "Notes" %>
 <%= render 'Homepage/navmenu' %> 
<!----------------------------------------breadcrumb section-------------------------------------->
        <div class="row p-3">
            <div class="breadcrumb-default ml-2">
                <%= link_to "#{params[:uni]}-#{params[:dept]}-#{params[:sub_dept]}-#{params[:sub]}", notes_path,class:"text-capitalize" %>
                    <a href="#" class="text-capitalize">/<%= params[:sem] %>-Notes</a>
            </div>
        </div>

<% if @chapters.to_a[0][1] == "Not Found" %>
	<div class="container">
		<pre class="responsive-text text-danger">Notes for this semester are not available. We will be adding them very soon. Thank You!!</pre>
	</div>
<% else %>
	<div class="container-fluid">
		<div class="row">
			<% @chapters.each do |chapter| %>
				<%
					chapter_number = chapter["name"].to_s.split("_")[0]
					chapter_name = chapter["name"].to_s.split("_")[1]
					filename = chapter_number + "_" + chapter_name
				%>
				<div class="col-6 col-md-3 text-center mt-2">
					<%= link_to notes_notes_download_path(download_url:chapter["download_url"],filename:filename), target: '_self',data: {disable_with: "Please wait..."} do %>
						<div class="card h-100">
					        <div class="card-body">
					            <i class="fas fa-file-pdf fa-2x text-danger"></i><br />
					            <i class="fas fa-download"></i>
					            <span class="text-capitalize responsive-text">
					            	<%= chapter_number %>
					            </span><br>
					            <span class="text-capitalize responsive-text">
					            	<% chapter["name"].to_s.split("_")[1].split(".")[0].split("-").each do |name| %>
					            		<%= name %>
					            	<% end %>
					            		
					            	</span>
					     	</div>
				    	 </div>
					<% end %>	
					</div>	
			<% end %> 
		</div>
	</div>
<% end %>

app/views/notes/notes_show.html.erb
<div class="card-columns">
        <% @subject.notes.each do |note| %>
            <div class="card ">
              <%= note.name %>
            </a>
                <a target="_blank" href="<%= note.note_pdf %>"><i class="fas fa-hand-point-right"></i> open</a><br/>
           </div>
        <% end %>
    </div>

app/views/notes/show.html.erb
<div class="card-columns">
        <% @subject.notes.each do |note| %>
            <div class="card ">
              <%= note.name %>
            </a>
                <a target="_blank" href="<%= note.note_pdf %>"><i class="fas fa-hand-point-right"></i> open</a><br/>
           </div>
        <% end %>
    </div>

app/views/notes/syllabus_index.html.erb
<% content_for :title, "Syllabus" %>
 <%= render 'Homepage/navmenu' %> 
<!----------------------------------------breadcrumb section-------------------------------------->
        <div class="row p-3">
            <div class="breadcrumb-default ml-2">
                <%= link_to "#{params[:uni]}-#{params[:dept]}-#{params[:sub_dept]}-#{params[:sub]}", notes_path,class:"text-capitalize" %>
                    <a href="#" class="text-capitalize">/<%= params[:sem] %>-Syllabus</a>
            </div>
        </div>
<!----------------------------------------------------------------------------------------------------->

<% if @syllabus.to_a[0][1] == "Not Found" %>
	<div class="container">
		<pre class="responsive-text text-danger">Syllabus for this semester are not available. We will be adding them very soon. Thank You!!</pre>
	</div>
<% else %>
	<div class="container-fluid">
		<div class="row">
			<% @syllabus.each do |syllabus| %>
				<%
					filename = params[:sub]+"syllabus"
				%>
				<div class="col-6 col-md-3 text-center mt-2">
					<%= link_to notes_notes_download_path(download_url:syllabus["download_url"],filename:filename), target: '_self',data: {disable_with: "Please wait..."} do %>
						<div class="card h-100">
					        <div class="card-body">
					            <i class="fas fa-file-pdf fa-2x text-danger"></i><br />
					            <i class="fas fa-download"></i>
					            <span class="text-capitalize responsive-text">
					            	<%= params[:sub] %>
					            </span><br>
					           
					     	</div>
				    	 </div>
					<% end %>	
					</div>	
			<% end %> 
		</div>
	</div>
<% end %>

app/views/notes/test.html.erb
<% content_for :title, "Notes" %>
<%= render 'Homepage/navmenu' %>

  <% @universities.each do |university| %>
      <div class="tree ">
        <ul>
          <li>
            <span>
              <a 
                style="color:#000; text-decoration:none;" 
                data-toggle="collapse" 
                href="#<%= university.name.to_s.delete(" ") %>" 
                aria-expanded="true" 
                aria-controls="<%= university.name.to_s.delete(" ") %>">
                <i class="collapsed"><i class="fas fa-folder"></i></i>
                <i class="expanded"><i class="far fa-folder-open"></i></i>
                 <%= university.name %>
                  </a>
              </span>
            
              <div id="<%= university.name.to_s.delete(" ") %>" class="collapse show">
                <ul>
                <!-------------------DEPARTMENTS------------------------------->
                <% university.university_departments.each do |department| %>
                  <li>
                    <span class="text-uppercase responsive-text">
                      <a 
                        style="color:#000;"
                        data-toggle="collapse"
                        href="#<%= university.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %>" 
                        aria-expanded="false" 
                        aria-controls="<%= university.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %>">

                        <i class="collapsed"><i class="fas fa-folder"></i></i>
                        <i class="expanded"><i class="far fa-folder-open"></i></i>
                        <%= department.name %>
                      </a>
                    </span>
                  <ul>
                    <div id="<%= university.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %>" class="collapse">
                      <ul>
                        <!-------sUB DEPARTMENTS---------->
                        <% department.sub_departments.each do |sub_department| %>
                        <li>
                          <span class="text-uppercase responsive-text">
                            <a 
                              style="color:#000;" 
                              data-toggle="collapse" 
                              href="#<%= university.name.to_s.delete(" ") %><%= sub_department.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %>" 
                              aria-expanded="false" 
                              aria-controls="<%= university.name.to_s.delete(" ") %><%= sub_department.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %>">

                              <i class="collapsed"><i class="fas fa-folder"></i></i>
                              <i class="expanded"><i class="far fa-folder-open"></i></i>
                              <%= sub_department.name %>

                            </a>
                          </span>
                          <div id="<%= university.name.to_s.delete(" ") %><%= sub_department.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %>" class="collapse">
                            <ul>
                              <!-------semesters---------->
                              <% @semesters.each do |semester| %>
                                  <li>
                                    <span class="responsive-text">
                                      <a 
                                      style="color:#000;" 
                                      data-toggle="collapse" 
                                      href="#<%= university.name.to_s.delete(" ") %><%= sub_department.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %><%= semester.name.to_s.delete(" ") %>" 
                                      aria-expanded="false" 
                                      aria-controls="<%= university.name.to_s.delete(" ") %><%= sub_department.name.to_s.delete(" ") %><%= department.name.to_s.delete(" ") %><%= semester.name.to_s.delete(" ")%>">
                                      
                                      <i class="collapsed"><i class="fas fa-folder"></i></i>
                                      <i class="expanded"><i class="far fa-folder-open"></i></i>
                                      <%= semester.name %>

                                    </a>
                                    </span>

                                  <div id="<%= university.name.name.to_s.delete(" ") %><%= sub_department.name.to_s.delete(" ") %><%= department.name.name.to_s.delete(" ") %><%= semester.name.name.to_s.delete(" ") %>" class="collapse">
                                    <ul>
                                      <!-------Subjects---------->
                                      <% semester.subjects.where("sub_department_id=?",sub_department.id).each do  |subject| %>
                                        <li>
                                          <span class="responsive-text">
                                          <a 
                                            style="color:#000;" 
                                            data-toggle="collapse" 
                                            href="#<%= university.name %><%= sub_department.name.to_s.delete(" ") %><%= department.name %>notes" 
                                            aria-expanded="false" 
                                            aria-controls="<%= university.name %><%= sub_department.name.to_s.delete(" ") %><%= department.name %>notes">

                                            <i class="collapsed"><i class="fas fa-folder"></i></i>
                                            <i class="expanded"><i class="far fa-folder-open"></i></i>
                                            <%= subject.name %>

                                          </a>
                                        </span>
                                          </li>
                                          <% end %>
                                    </ul>
                                  </div>
                                  </li>
                                  <% end %>
                            </ul>
                          </div>  
                      </li>

                      <% end %>

                      </ul>
                    </div>              
                    </ul>
                  </li>
                  <% end %>
                </ul>
              </div>
          </li>
        </ul>

      </div>
  <% end %>
<!-------------------------------------------------------------------------------------------->