config/routes.rb
Rails.application.routes.draw do

  get 'documents/index'
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'telephone_directory/index'

  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'homes/show', to:"homes#show"
  get 'homes/index', to:"homes#index"
  get 'homes/tool', to:"homes#tool"
  get 'homes/search', to:"homes#search"

  # utility
  get 'homes/dateConverter', to:"homes#dateConverter"
  get 'homes/currency', to:"homes#currency"
  get 'homes/freeConverter', to:"homes#freeConverter"
  get 'homes/goldSilver', to:"homes#goldSilver"
  get 'homes/nepaliCalendar', to:"homes#nepaliCalendar"
  get 'homes/panchang', to:"homes#panchang"
  get 'homes/rashifall', to:"homes#rashifall"
  get 'homes/unicode', to:"homes#unicode"
  get 'homes/weather', to:"homes#weather"
  get 'homes/document', to:"homes#document"

  get 'set_mylanguage/np', to:"set_mylanguage#np"
  get 'set_mylanguage/en', to:"set_mylanguage#en"

  get 'realestates/rent', to:"realestates#rent"
  get 'realestates/sell', to:"realestates#sell"

  get 'aboutus/index', to:"aboutus#index"
  get 'contactus/index', to: "contactus#index"
  get 'contactus/new', to: "contactus#new"

   get 'listings/show', to:"listings#show"
   get 'listings/new', to:"listings#new"
   post 'listings/new', to:"listings#new"
   post 'listings/create', to:"listings#create"
   get 'notes/notes_show'


   resources :bus_departures, only: [:index]
   resources :models, only: [:index, :show]
   resources :events,only: [:index,:new,:create]
   resources :marketplaces,:professionals
   resources :notes, only: [:index]
   resources :gamifications, only: [:index]
   resources :statistics, only: [:index]
   resources :projects, only: [:index,:show]
   resources :tags, only: [:index]

   get 'notes/notes_index'
   get 'notes/notes_download'
   get 'notes/syllabus_index'
   get 'gamifications/reward'

   
   #routes for statistics
  
   get 'statistics/bhimdatt_index'
   get 'statistics/punarbas_index'
   get 'statistics/krishnapur_index'
   get 'statistics/mahakali_index'
   get 'statistics/suklaphata_index'
   get 'statistics/belauri_index'
   get 'statistics/betkot_index'
   get 'statistics/laljhadi_index'
   get 'statistics/beldadi_index'

   #routes for arcy#
   resources :donors
   resources :vacancies
   resources :pet_adoptions
   resources :documents
   resources :sections

   #################



   get 'listings/sucess', to: "listings#sucess"

   resources :agents, only: [:index]


  root 'homes#index'
  resources :realestates
  resources :tourists
 

  resources :listings do
      resources :reviews
  end
  resources :projects do
      resources :donations
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  mount SimpleDiscussion::Engine => "/forum"

  #mnr forum
  resources :poll_votes
  resources :posts do
    resources :post_comments
    member do
      put "like" => "posts#upvote"
      put "dislike" => "posts#downvote"
      put "follow" => "posts#follow"
      put "unfollow" => "posts#unfollow"
    end
  end

  mount ActionCable.server => '/cable'

  #for API
  mount API::Base, at: "/"

end

app/models/tourist.rb
class Tourist < ApplicationRecord

    
    has_many :tourist_images, dependent: :destroy
    extend FriendlyId
    
    friendly_id :place_name, use: :slugged
    
    def to_s 
        return self.place_name 
    end 
    def title 
        return self.to_s
    end 
    accepts_nested_attributes_for :tourist_images, :reject_if => proc {|attributes| attributes['image'].blank? && attributes['image_cache'].blank?}

    #for search
    include AlgoliaSearch
	  algoliasearch auto_index: true do
	    attribute :place_name
	    searchableAttributes ['place_name']
	  end

end

app/controllers/api/v1/tourists.rb
module API
    module V1
        class Tourists < Grape::API
            include API::V1::Defaults
            resource :tourists do
                desc "Return all Tourists"
                    get do
                        Tourist.order(:created_at)
                    end
            end
        end
    end
end

app/controllers/tourists_controller.rb
class TouristsController < ApplicationController
  
  before_action :set_tourist, only: [:show , :destroy, :edit, :update]
  
  def index 
        @tourist=Tourist.order(:place_name)
    end 
     
    def show
      @tourist = Tourist.friendly.find(params[:id])
    end

    def new
      @tourist = Tourist.new
      @tourist_image = @tourist.tourist_images.build

    end 

    def create 
      @tourist = Tourist.new(tourist_params)

        if @tourist.save
            params[:tourist_images]['image'].each do |a|
            @tourist_image = @tourist.tourist_images.create!(:image => a)
          end

            if user_signed_in?
                current_user.gamification.create!(points:5)
             end
            redirect_to tourists_path
          else
            render :new 
        end 

    end 

    def edit 
      @tourist = Tourist.friendly.find(params[:id])
    end 

    def update 
      if @tourist.update(tourist_params)
        redirect_to @tourist
      else
        render :edit
      end 

    end 

    def destroy
      if @tourist.destroy
        redirect_to @tourist
      end 
    end 

  

    private
    def set_tourist 
      @tourist = Tourist.friendly.find(params[:id])
    end

    def tourist_params
      params.require(:tourist).permit(:place_name, :location, :contact, :longitude, :lattitude, :feature, :description,  tourist_images_attributes: [:id, :tourist_id, :image, :image_cache])
          
        
    end 

end

app/helpers/tourists_helper.rb
module TouristsHelper
end

app/views/tourists/_form.html.erb
	<%= form_for @tourist,:html => { :multipart => true,class:"needs-validation", :novalidate=>true } do |f| %>

                <!--------------Errors-------------------------------------->
        <% if @tourist.errors.any? %>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            <% @tourist.errors.full_messages.each do |message|%>
                <p class="responsive-text"><%= message %> </p>
              <%end%>
          </div>
        <%end%>
        <!------------------------------form fields ------------------------------------------------->

		
        <div class="input-group has-validation">
            <%= f.text_field :place_name, placeholder: " #{t('tourist_placeholder1')}  ", class:"form-control MT-2", required:true %>
            <div class="invalid-feedback">
                Please enter a valid Place  Name.
            </div>
        </div>
        <div class="input-group has-validation">
            <%= f.text_field :location, placeholder: "#{t('tourist_placeholder2')} ", class:"form-control mt-2", required:true %>
            <div class="invalid-feedback">
                Please enter a valid Location.
            </div>
        </div>
        <div class="input-group has-validation">
            <%= f.telephone_field :contact, placeholder: "#{t('tourist_placeholder3')}", class:"form-control mt-2" %>
            <div class="invalid-feedback">
                Please enter a valid Phone number.
            </div>
        </div>
        <div class="input-group has-validation">
            <%= f.text_field :longitude, placeholder: "#{t('tourist_placeholder4')}", class:"form-control mt-2" %>
            <div class="invalid-feedback">
                Please enter  valid longitude of place .
            </div>
        </div>
                <div class="input-group has-validation">
            <%= f.text_field :lattitude, placeholder: "#{t('tourist_placeholder5')}", class:"form-control mt-2" %>
            <div class="invalid-feedback">
                Please enter valid latitude of place.
            </div>
        </div>
                <div class="input-group has-validation">
            <%= f.text_area :feature, placeholder: "#{t('tourist_placeholder6')}", class:"form-control mt-2", :rows => "3", required:true %>
            <div class="invalid-feedback">
                Please enter some features about place .
            </div>
        </div>
        <div>
                <div class="input-group has-validation">
            <%= f.text_area :description, placeholder: "  #{t('tourist_placeholder7')} ", class:"form-control mt-2", :rows => "4", required:true %>
            <div class="invalid-feedback">
                Please enter some description about place .
            </div>
        </div>
        <!-------------image section ------------------------------------------------------>
        <hr />
        <label class="mr-2"> </label>
         <div class="row p-2">
                <strong> <%= t('tourist_placeholder8') %> </strong>
            <%= f.fields_for :tourist_images do |p| %>
                <div class="input-group has-validation">
                <%= p.file_field :image , direct_upload: true,:multiple => true,class:"form-control",name:"tourist_images[image][]",required:true %>
                 <%= p.hidden_field :image_cache %>
                 <div class="invalid-feedback">
                    Please uplaod Place  Images.
                 </div>
             </div>
             <pre> <%= t('tourist_placeholder9') %> </pre>
            <% end %>
           </div>
        <hr />
         <!-------------form buttons-------------------->
          <div class="d-flex flex-row mt-2">
            <div class="flex-fill">
              <%= link_to :back do %>
                <span class="cancel-button form-control font-weight-bold text-center"> <%= t('cancel') %> </span>
              <% end %>
            </div>
            <div class="flex-fill">
              <%= f.submit " #{t('save')}" , class:"button form-control font-weight-bold", data: { disable_with: "Adding..." } %>
            </div>
          </div>
           <%= recaptcha_action('marketplace') %>
  <% end %>

app/views/tourists/edit.html.erb
<%= content_for :recaptcha_js do %>
    <%= include_recaptcha_js %>
  <% end %>
  <%= render 'Homepage/navmenu' %>
  
          <div class="container">
                <h1 class="form_title"> Edit Tourist Places to   <span class="mnryp_word">MNRYP</span></h1>
                   
            <div class="row">
              <div class="col-md-6">
                <ul >
                    <li class="about-paddingB text-justify"> The Entered Tourists Places must exists </li>
                    <li class="about-paddingB text-justify"> You can multiple Images about Place</li>
                    <li class="about-paddingB text-justify"> The Image of Place must as same as the Real Place</li>
                    <li class="about-paddingB text-justify"> Enter Phone Number Related to Place so that visitors would able contact to corresponding people</li>
                    <li class="about-paddingB text-justify"> Longitude and latitude of place are used to show place in the google map below </li>
                    <li class="about-paddingB text-justify"> Longitude & Latitude : you can get your place's longitue and latitude by opening google maps(at the place area) in your phone or laptop </li>
                    
                </ul>
              </div>
              <div class="col-md-6">
              <div class="shadow p-3 mb-5 bg-white rounded">
              <%= render partial:"form" %>
              </div>
              </div>
            </div>
         </div>

app/views/tourists/index.html.erb
 <%= render 'Homepage/navmenu' %>

    <% if user_signed_in? %>
        <div class="mt-4 ml-4 mb-2">
            <%= link_to new_tourist_path, style:"text-decoration:none; font-size: 20px;" do %>
                <%= t('add_new_places') %>
            <i class="fas fa-plus-circle ml-2"></i>
            <% end %>  
        </div>
        <% else %>
        <div class="mt-4 ml-4 mb-2">
            <%= link_to user_session_path do %>
            <span  class=" btn-outline-danger rounded p-2 border"> <%= t('sign_in_to_add_tourist') %>  </span>
            <% end %>
        </div>
    <% end %>
  
  <!------------------tourism cards started---------------------------------->
    
    <div id="cards_landscape_wrap-2">
        <div class="container">
        <h1 style="color:green;"> <strong>   Places To Visit   </strong> </h1>
            <div class="row">  
            <% @tourist.each do |tourist| %>
               
                <div class="col-md-3">
                <%=  link_to  tourist_path(tourist), style:"text-decoration:none" do %>
                        <div class="card-flyer ">
                            <div class="text-box">
                                <div class="image-box">
                                <% tourist.tourist_images.each do |place_img| %>
                                    <%= cl_image_tag(place_img.image, :quality=>"auto:low",:fetch_format=>"auto",:flags=>"lossy" , :class=>"card-image", loading:"lazy" ) %>
                                    <% break %>
                                <% end %>
                                </div>
                                <div class="text-container text-black ">
                                    <h6 ><%= tourist.place_name %></h6>
                                         <p>  <i class="fas fa-map-marker-alt"></i> <%= tourist.location%></p>
                                </div>
                                <!----------if user is signed in as well as admin only then delete and edit buttons are available-------------->
                                <% if user_signed_in? && current_user.admin? && current_user.id  %> <div class="d-flex flex-row-reverse p-2">
                                        <div>
                                            <%= link_to  tourist, method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fas fa-trash-alt text-danger"></i><% end %>
                                        </div>
                                        <div class="mr-2 ml-2">
                                            <%= link_to  edit_tourist_path(tourist) do %><i class="far fa-edit text-primary"></i><% end %>
                                        </div>
                                    </div>
                                   
                                <% end %>
                                <!--------------------------------------------------------------------------------------------------------->
                            </div>
                        </div>
                </div>
              <% end %>

           <% end %>     
            </div>
        </div>
                
    </div>

 

       
   <!-----------------tourism cards end----------------------------------------------->

app/views/tourists/new.html.erb
<%= content_for :recaptcha_js do %>
    <%= include_recaptcha_js %>
  <% end %>
  <%= render 'Homepage/navmenu' %>
  
          <div class="container">
                <h1 class="form_title"> <%= t('tourist_title') %>   <span class="mnryp_word">MNRYP</span></h1>
                   
            <div class="row">
              <div class="col-md-6">
                <ul >
                    <li class="about-paddingB text-justify"> <%= t('tourist_text1') %> </li>
                    <li class="about-paddingB text-justify"> <%= t('tourist_text2') %> </li>
                    <li class="about-paddingB text-justify"> <%= t('tourist_text3') %> </li>
                    <li class="about-paddingB text-justify"> <%= t('tourist_text4') %> </li>
                    <li class="about-paddingB text-justify"> <%= t('tourist_text5') %> </li>
                    <li class="about-paddingB text-justify"> <%= t('tourist_text6') %> </li>
                    <li class="about-paddingB text-justify"> <%= t('tourist_text7') %> </li>
                    
                </ul>
              </div>
              <div class="col-md-6">
              <div class="shadow p-3 mb-5 bg-white rounded">
              <%= render partial:"form" %>
              </div>
              </div>
            </div>
         </div>
   

app/views/tourists/show.html.erb
 <%= render 'Homepage/navmenu' %>
 <div class="row px-4">
        <div class="col-md-6">  
            <!------------carousel start ------------------------------------------------->
                <div  id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <% @tourist.tourist_images.each_with_index do |place_img,index| %>
                            <% active_class = "active" if index == 0 %>
                            <div class="carousel-item <%= active_class %>">
                            <%= cl_image_tag(place_img.image, :quality=>"auto:low",:fetch_format=>"auto",:flags=>"lossy" , :class=>"carousel-img", loading:"lazy") %>
                            </div>
                        <% end %>
                    </div>
                <!---------------for carousel controls --------------------->
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
            <!--------------------------------------------------------------------->
      </div>
      
         <!------------carousel end ------------------------------------------------->
        </div>
        <div class="col-md-6">
            <h2>
                <strong><%= @tourist.place_name %></strong>
            </h2>
            <p>
                <span class="badge badge-info"> <%= t('contact') %> </span>
            </p>
                <p class="card-text"><i class="fas fa-map-marker-alt"></i>&nbsp;<%= @tourist.location %></p>
                <p class="card-text"><i class="fas fa-phone-alt"></i>&nbsp;<%= @tourist.contact %></p>
                <i class="fas fa-check-double"></i> <strong> <%= t('description_and_features') %> :</strong> <br>
                        
                    <% splitted=@tourist.feature.split(',') %>
                    <% splitted.each do|feature| %>
                        <span class="badge rounded-pill bg-success"> <%= feature %></span>
                        
                    <% end %>
                    
        </div>
</div>
<!--------------------------for tab ---------------------------------------------------------------->
        <div class="container-fluid mt-2">
            <div class="row">
                <div class="col-md-12">
                    <nav>
                        <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
                            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true" style="text-decoration:none;"> <%= t('location') %> </a>
                            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false" style="text-decoration:none;"> <%= t('about_place')%> </a>
                        </div>
                    </nav>
                    <div class="tab-content" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                            <table class="table" cellspacing="0">
                                <!--The div element for the map ----------------------->
                                    <strong> <i class="fas fa-map-marked-alt"></i> <%= t('gmap') %> </strong> <br>
                                    <% lat = @tourist.lattitude %>
                                    <% long = @tourist.longitude %>
                                    <div class="embed-responsive embed-responsive-16by9">
                                    <iframe class="embed-responsive-item" src="https://maps.google.com/maps?q=<%= lat %>,<%= long %>&z=15&output=embed" loading="lazy" allowfullscreen></iframe>
                                    </div>
                                <!--------------------map section ends-------------------------------->                            </table>
                        </div>
                        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                            <table class="table" cellspacing="0">
                            <p> <strong><h5><%= @tourist.description %> <strong></p>      
                            </table>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

<style> 
.carousel-inner{
    width:100%;
    max-height: 400px !important; 
}
.carousel-img{
    width : 100%;
    height: 500px;
}

</style>