config/routes.rb
Rails.application.routes.draw do

  get 'documents/index'
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'telephone_directory/index'

  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'homes/show', to:"homes#show"
  get 'homes/index', to:"homes#index"
  get 'homes/tool', to:"homes#tool"
  get 'homes/search', to:"homes#search"

  # utility
  get 'homes/dateConverter', to:"homes#dateConverter"
  get 'homes/currency', to:"homes#currency"
  get 'homes/freeConverter', to:"homes#freeConverter"
  get 'homes/goldSilver', to:"homes#goldSilver"
  get 'homes/nepaliCalendar', to:"homes#nepaliCalendar"
  get 'homes/panchang', to:"homes#panchang"
  get 'homes/rashifall', to:"homes#rashifall"
  get 'homes/unicode', to:"homes#unicode"
  get 'homes/weather', to:"homes#weather"
  get 'homes/document', to:"homes#document"

  get 'set_mylanguage/np', to:"set_mylanguage#np"
  get 'set_mylanguage/en', to:"set_mylanguage#en"

  get 'realestates/rent', to:"realestates#rent"
  get 'realestates/sell', to:"realestates#sell"

  get 'aboutus/index', to:"aboutus#index"
  get 'contactus/index', to: "contactus#index"
  get 'contactus/new', to: "contactus#new"

   get 'listings/show', to:"listings#show"
   get 'listings/new', to:"listings#new"
   post 'listings/new', to:"listings#new"
   post 'listings/create', to:"listings#create"
   get 'notes/notes_show'


   resources :bus_departures, only: [:index]
   resources :models, only: [:index, :show]
   resources :events,only: [:index,:new,:create]
   resources :marketplaces,:professionals
   resources :notes, only: [:index]
   resources :gamifications, only: [:index]
   resources :statistics, only: [:index]
   resources :projects, only: [:index,:show]
   resources :tags, only: [:index]

   get 'notes/notes_index'
   get 'notes/notes_download'
   get 'notes/syllabus_index'
   get 'gamifications/reward'

   
   #routes for statistics
  
   get 'statistics/bhimdatt_index'
   get 'statistics/punarbas_index'
   get 'statistics/krishnapur_index'
   get 'statistics/mahakali_index'
   get 'statistics/suklaphata_index'
   get 'statistics/belauri_index'
   get 'statistics/betkot_index'
   get 'statistics/laljhadi_index'
   get 'statistics/beldadi_index'

   #routes for arcy#
   resources :donors
   resources :vacancies
   resources :pet_adoptions
   resources :documents
   resources :sections

   #################



   get 'listings/sucess', to: "listings#sucess"

   resources :agents, only: [:index]


  root 'homes#index'
  resources :realestates
  resources :tourists
 

  resources :listings do
      resources :reviews
  end
  resources :projects do
      resources :donations
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  mount SimpleDiscussion::Engine => "/forum"

  #mnr forum
  resources :poll_votes
  resources :posts do
    resources :post_comments
    member do
      put "like" => "posts#upvote"
      put "dislike" => "posts#downvote"
      put "follow" => "posts#follow"
      put "unfollow" => "posts#unfollow"
    end
  end

  mount ActionCable.server => '/cable'

  #for API
  mount API::Base, at: "/"

end

app/models/marketplace.rb
class Marketplace < ApplicationRecord

	include ActiveModel::Validations

	extend FriendlyId
    
  	friendly_id :prod_name, use: :slugged
    
    has_many :market_place_images,dependent: :destroy
    accepts_nested_attributes_for :market_place_images, :reject_if => proc {|attributes| attributes['image'].blank? && attributes['image_cache'].blank?}
    
    validates_presence_of :prod_name, :seller_name, :price, :phone, :description, :user_id
    validates_numericality_of :phone
  	validates_length_of :phone, is: 10
end

app/controllers/api/v1/marketplaces.rb
module API
    module V1
        class Marketplaces < Grape::API
            include API::V1::Defaults
            resource :marketplaces do
                desc "Return all Marketplaces"
                    get do
                        Marketplace.order(:created_at)
                    end
            end
        end
    end
end

app/controllers/marketplaces_controller.rb
class MarketplacesController < ApplicationController

    before_action :set_marketplace, only: [:show, :edit, :update, :destroy]

	def index
		@marketplaces = Marketplace.includes(:market_place_images)
	end

  def show
    @marketplace = Marketplace.friendly.find(params[:id])
  end
	def new
		@marketplace = Marketplace.new
    @marketplace_image = @marketplace.market_place_images.build
	end
	def create
        @marketplace = Marketplace.new(marketplace_params)
    
        respond_to do |format|
             if @marketplace.save
                    params[:market_place_images]['image'].each do |a|
                    @marketplace_image = @marketplace.market_place_images.create!(:image => a, :marketplace_id => @marketplace.id)
                  end

                    if user_signed_in?
                        current_user.gamification.create!(points:5)
                     end
                    format.html { redirect_to marketplaces_path notice: 'Product was successfully added.' }
              else
                    format.html { render :new }
              end
        end
  end

  def edit
    @marketplace = Marketplace.friendly.find(params[:id])
  end

  def update
    respond_to do |format|
      if @marketplace.update(marketplace_params)
        format.html { redirect_to @marketplace, notice: 'Product was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @marketplace.destroy
    respond_to do |format|
      format.html { redirect_to marketplaces_url, notice: 'Product was successfully destroyed.' }
    end
  end
    
      private
         def set_marketplace
            @marketplace = Marketplace.friendly.find(params[:id])
         end

        def marketplace_params
          params.require(:marketplace).permit(:prod_name, :seller_name, :price, :phone,:description,:user_id,market_place_images_attributes: [:id, :marketplace_id, :image, :image_cache])
        end
end

app/helpers/marketplaces_helper.rb
module MarketplacesHelper
end

app/views/marketplaces/_form.html.erb
	<%= form_for @marketplace,:html => { :multipart => true,class:"needs-validation", :novalidate=>true } do |f| %>

                <!--------------Errors-------------------------------------->
        <% if @marketplace.errors.any? %>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            <% @marketplace.errors.full_messages.each do |message|%>
                <p class="responsive-text"><%= message %> </p>
              <%end%>
          </div>
        <%end%>
        <!------------------------------------------------------------------------------->


		<%= f.hidden_field :seller_name, value:"#{current_user.name}" %>
		<%= f.hidden_field :user_id, value:"#{current_user.id}" %>

        <div class="input-group has-validation">
            <%= f.text_field :prod_name, placeholder: "#{t('marketplace_placeholer_1')}", class:"form-control MT-2" %>
            <div class="invalid-feedback">
                Please enter a valid Product Name.
            </div>
        </div>
        <div class="input-group has-validation">
            <%= f.number_field :price, placeholder: "#{t('marketplace_placeholer_2')}", class:"form-control mt-2" %>
            <div class="invalid-feedback">
                Please enter a valid Price.
            </div>
        </div>
        <div class="input-group has-validation">
            <%= f.telephone_field :phone, placeholder: "#{t('marketplace_placeholer_3')}", class:"form-control mt-2" %>
            <div class="invalid-feedback">
                Please enter a valid Phone number.
            </div>
        </div>
        <div class="input-group has-validation">
            <%= f.text_area :description, placeholder: "#{t('marketplace_placeholer_4')}", class:"form-control mt-2" %>
            <div class="invalid-feedback">
                Please enter a valid Bussiness Address.
            </div>
        </div>

        <hr />
        <label class="mr-2"><%= t('marketplace_placeholer_5') %></label>
         <div class="row p-2">
            <%= f.fields_for :market_place_images do |p| %>
                <div class="input-group has-validation">
                <%= p.file_field :image, direct_upload: true,:multiple => true,class:"form-control",name:"market_place_images[image][]",required:true %>
                 <%= p.hidden_field :image_cache %>
                 <div class="invalid-feedback">
                    Please uplaod Product Images.
                 </div>
             </div>
             <pre><%= t('marketplace_placeholer_6') %></pre>
            <% end %>
           </div>
        <hr />
         <!-------------form buttons-------------------->
          <div class="d-flex flex-row mt-2">
            <div class="flex-fill">
              <%= link_to :back do %>
                <span class="cancel-button form-control font-weight-bold text-center">Cancel</span>
              <% end %>
            </div>
            <div class="flex-fill">
              <%= f.submit "Save" , class:"button form-control font-weight-bold", data: { disable_with: "Saving..." } %>
            </div>
          </div>
           <%= recaptcha_action('marketplace') %>
  <% end %>

app/views/marketplaces/edit.html.erb
<%= content_for :recaptcha_js do %>
    <%= include_recaptcha_js %>
  <% end %>
  <%= render 'Homepage/navmenu' %>
  
      <div id="addlistform" class="about-section paddingTB60 gray-bg">
          <div class="container">
              <div class="row">
                <div class="row">
                <div class="col-md-12 col-sm-12">
                   <div class="about-title clearfix">
                      <h1>Sell your Product through <span>MNRYP</span></h1>
                   </div>
                </div>
              </div>
            </div>
            <div class="row">
            <div class="col-md-6 col-sm-12">
            <ul >
              <li class="about-paddingB text-justify">Provide accurate details.</li>
              <li class="about-paddingB text-justify">The seller and buyer will be responsible for all transactions.</li>
              <li class="about-paddingB text-justify">Your products will be listed for a period of one month.</li>
            </ul>
            </div>
                <div class="col-md-6 col-sm-12">
                <div class="shadow p-3 mb-5 bg-white rounded">
                <%= render partial:"form" %>
                </div>
                </div>
            </div>
         </div>
       </div>
   
       
       

app/views/marketplaces/index.html.erb
<% content_for :title, "MNR Marketplace-MNRYP" %>
<%= render 'Homepage/navmenu' %>

<% if user_signed_in? %>
    <div class="mt-4 ml-4 mb-2">
        <%= link_to new_marketplace_path, style:"text-decoration:none; font-size: 20px;" do %>
            <%= t('add_product') %>
        <i class="fas fa-plus-circle ml-2"></i>
    	<% end %>  
    </div>
<% else %>
    <div class="mt-4 ml-4 mb-2">
        <%= link_to user_session_path do %>
        <span  class=" btn-outline-danger rounded p-2 border">  <%= t('login_to_sell') %> </span>
        <% end %>
    </div>
<% end %>

<!-- Topic Cards -->
    <div class="container">
        <div class="row">
            <% @marketplaces.each do |marketplace| %>
                <div class="col-md-3">
                	<div class="card h-100">
                        <% marketplace.market_place_images.each do |prod_img| %>
                    		<%= cl_image_tag(prod_img.image, :quality=>"auto:low",:fetch_format=>"auto",:flags=>"lossy" , :class=>"card-image", loading:"lazy") %>
                            <% break %>
                        <% end %>
				        <div class="card-body">
				          <h4 class="card-title"><%= marketplace.prod_name %></h4>
				          <h6 class="card-subtitle mb-2 text-muted">Seller: <%= marketplace.seller_name %></h6>
				          <div class="buy d-flex justify-content-between align-items-center">
				            <div class="text-success"><h5 class="">Rs.<%= marketplace.price %></h5></div>
				          </div>
    				          <a href="tel:<%= marketplace.phone %>" class="mt-2"><i class="fas fa-phone-alt"></i> <%= marketplace.phone %></h6></a>
                              <%= link_to marketplace_path(marketplace), class:"float-right" do %>
                               View More
                              <% end %>
                        
                                <% if user_signed_in? && current_user.id == marketplace.user_id %>
                                    <div class="d-flex flex-row-reverse p-2">
                                        <div>
                                            <%= link_to  marketplace, method: :delete, data: { confirm: 'Are you sure?' } do %><i class="fas fa-trash-alt text-danger"></i><% end %>
                                        </div>
                                        <div class="mr-2 ml-2">
                                            <%= link_to  edit_marketplace_path(marketplace) do %><i class="far fa-edit text-primary"></i><% end %>
                                        </div>
                                    </div>
                                <% end %>
				      </div>
                </div>
            </div>
            <% end %>
        </div>
    </div>

app/views/marketplaces/new.html.erb
<%= content_for :recaptcha_js do %>
    <%= include_recaptcha_js %>
  <% end %>
  <%= render 'Homepage/navmenu' %>
  
          <div class="container">
                <h1 class="form_title"><%= t('marketplace_title') %> <span class="mnryp_word">MNRYP</span></h1>
                   
            <div class="row">
              <div class="col-md-6">
                <ul >
                    <li class="about-paddingB text-justify"><%= t('marketplace_text_1') %></li>
                    <li class="about-paddingB text-justify"><%= t('marketplace_text_2') %></li>
                    <li class="about-paddingB text-justify"><%= t('marketplace_text_3') %></li>
                    <span class="about-paddingB text-justify"><%= t('thanks_text') %></span>
                </ul>
              </div>
              <div class="col-md-6">
              <div class="shadow p-3 mb-5 bg-white rounded">
              <%= render partial:"form" %>
              </div>
              </div>
            </div>
         </div>
   

app/views/marketplaces/show.html.erb
<% content_for :title, "MNR Marketplace-MNRYP" %>
<%= render 'Homepage/navmenu' %>

<div class="container">
    <div class="row mt-4">
        <div class="col-md-6 text-center border-right border-secondery">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
			  <div class="carousel-inner">
			  	<% @marketplace.market_place_images.each_with_index do |prod_img,index| %>
			  		<% active_class = "active" if index==0 %>
			  		<div class="carousel-item <%= active_class %>">
			    	<%= cl_image_tag(prod_img.image, :quality=>"auto:low",:fetch_format=>"auto",:flags=>"lossy" , :class=>"carousel-img", loading:"lazy") %>
			    	</div>
			  	<% end %>
			  </div>
			  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
			    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
			    <span class="carousel-control-next-icon" aria-hidden="true"></span>
			    <span class="sr-only">Next</span>
			  </a>
			</div>
        </div>
        <div class="col-md-6">
            <h5>
                <%= @marketplace.prod_name %>
            </h5>
            <h3>
                Rs.<%= @marketplace.price %>
            </h3>
            <p>
                Seller: <%= @marketplace.seller_name %>
            </p>	
				<a href="tel:<%= @marketplace.phone %>" class="mt-2"><i class="fas fa-phone-alt"></i> <%= @marketplace.phone %></h6></a>
				<hr />
			<h4>Description</h4>
			<h6 class="text-justify"><%= @marketplace.description %></h6>
        </div>
    </div>
<div class="alert alert-danger text-justify" role="alert">
		<%= t('alert_message') %>

</div>
    
</div>
  <style>.carousel-inner{
  width:100%;
  max-height: 400px !important;
}
.carousel-img{
	width: 100%;
	height: 400px;
}
</style>