config/routes.rb
Rails.application.routes.draw do

  get 'documents/index'
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'telephone_directory/index'

  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'homes/show', to:"homes#show"
  get 'homes/index', to:"homes#index"
  get 'homes/tool', to:"homes#tool"
  get 'homes/search', to:"homes#search"

  # utility
  get 'homes/dateConverter', to:"homes#dateConverter"
  get 'homes/currency', to:"homes#currency"
  get 'homes/freeConverter', to:"homes#freeConverter"
  get 'homes/goldSilver', to:"homes#goldSilver"
  get 'homes/nepaliCalendar', to:"homes#nepaliCalendar"
  get 'homes/panchang', to:"homes#panchang"
  get 'homes/rashifall', to:"homes#rashifall"
  get 'homes/unicode', to:"homes#unicode"
  get 'homes/weather', to:"homes#weather"
  get 'homes/document', to:"homes#document"

  get 'set_mylanguage/np', to:"set_mylanguage#np"
  get 'set_mylanguage/en', to:"set_mylanguage#en"

  get 'realestates/rent', to:"realestates#rent"
  get 'realestates/sell', to:"realestates#sell"

  get 'aboutus/index', to:"aboutus#index"
  get 'contactus/index', to: "contactus#index"
  get 'contactus/new', to: "contactus#new"

   get 'listings/show', to:"listings#show"
   get 'listings/new', to:"listings#new"
   post 'listings/new', to:"listings#new"
   post 'listings/create', to:"listings#create"
   get 'notes/notes_show'


   resources :bus_departures, only: [:index]
   resources :models, only: [:index, :show]
   resources :events,only: [:index,:new,:create]
   resources :marketplaces,:professionals
   resources :notes, only: [:index]
   resources :gamifications, only: [:index]
   resources :statistics, only: [:index]
   resources :projects, only: [:index,:show]
   resources :tags, only: [:index]

   get 'notes/notes_index'
   get 'notes/notes_download'
   get 'notes/syllabus_index'
   get 'gamifications/reward'

   
   #routes for statistics
  
   get 'statistics/bhimdatt_index'
   get 'statistics/punarbas_index'
   get 'statistics/krishnapur_index'
   get 'statistics/mahakali_index'
   get 'statistics/suklaphata_index'
   get 'statistics/belauri_index'
   get 'statistics/betkot_index'
   get 'statistics/laljhadi_index'
   get 'statistics/beldadi_index'

   #routes for arcy#
   resources :donors
   resources :vacancies
   resources :pet_adoptions
   resources :documents
   resources :sections

   #################



   get 'listings/sucess', to: "listings#sucess"

   resources :agents, only: [:index]


  root 'homes#index'
  resources :realestates
  resources :tourists
 

  resources :listings do
      resources :reviews
  end
  resources :projects do
      resources :donations
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  mount SimpleDiscussion::Engine => "/forum"

  #mnr forum
  resources :poll_votes
  resources :posts do
    resources :post_comments
    member do
      put "like" => "posts#upvote"
      put "dislike" => "posts#downvote"
      put "follow" => "posts#follow"
      put "unfollow" => "posts#unfollow"
    end
  end

  mount ActionCable.server => '/cable'

  #for API
  mount API::Base, at: "/"

end

app/models/tag.rb
class Tag < ApplicationRecord


	include Translatable
	translates :title
	  
    mount_uploader :image, TagimageUploader
    has_many :listings, dependent: :destroy

    #for search
    include AlgoliaSearch
	  algoliasearch auto_index: true do
	    attribute :title_en
	    searchableAttributes ['title_en']
	  end

end

app/controllers/api/v1/tags.rb
module API
    module V1
        class Tags < Grape::API
            include API::V1::Defaults
            resource :tags do
            desc "Return all tags"
                get "" do
                    Tag.order(:title_en)
                end 
            end
        end
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		if  I18n.locale.to_s == "en"
	      @tags=Rails.cache.fetch('tags', expires_in: 2.days){Tag.order(:title_en)}
	    else
	      @tags = Rails.cache.fetch('tags', expires_in: 2.days){Tag.order(:title_np)}
	    end
	    @list_count = Rails.cache.fetch('list_counts', expires_in: 2.days){Listing.all.count}
	end
	
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<%= render 'Homepage/navmenu' %>

<div class="container mt-2">
	<div class="row">
		<div class="col-md-6">
			<span class="mnryp_word"><%= t('all_listings') %></span>
		</div>
		<div class="col-md-6">
			<input type="text" class="form-control form-control-md" placeholder="Search For Business" id="business_search" onkeyup="tagsFilter()">
		</div>
	</div>
</div>
<div class="m-2">
  <i id="noresult" class="text-danger" style="display: none;">No Businesses for your search!! Try searching something else!!</i>
</div>

<div class="container-fluid mx-2 mt-2">
    <div class="row" id="myItems">
    <% @tags.each do |tag| %>
            <div class="col-12 col-md-3 mt-2 filtercard">
                <%= link_to homes_show_path(category: tag.title_en ),:style=>'text-decoration:none' do%>
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex">
                            <div class="">
                                <% if tag.image.present? %>
                                    <%= cl_image_tag(tag.image, :quality=>"auto:low",:fetch_format=>"auto",:flags=>"lossy",:class=>"profile2 rounded-circle",loading:"lazy") %>
                                <%end%>
                            </div>
                            <div class="text-wrap">
                                <h6 class="card-category-title ml-2 mt-2"><%= tag.title %></h6>
                                <span class="business_tag sr-only"><%= tag.title_en %></span>
                            </div>
                            <div class="ml-auto">
                                <span class="badge badge-info"><%= tag.listings_count %></span>
                            </div>
                        </div>
                    </div>
                    </div>
                     <% end %>
             </div>    
    <%end%>
</div>
</div>

<script type="text/javascript">
	
	function tagsFilter(){

      input = document.getElementById("business_search");
      filter_place = input.value.toUpperCase();

      cardContainer = document.getElementById("myItems");
      cards = cardContainer.getElementsByClassName("filtercard");
      count=0
      for (i = 0; i < cards.length; i++) {
        business_tag = cards[i].querySelector(".card-body .business_tag");

        if (business_tag.innerText.toUpperCase().indexOf(filter_place) > -1) {
            count+=1
            cards[i].style.display = "";
        } else {
                cards[i].style.display = "none";
            }
        }
        if (count === 0){
          document.getElementById("noresult").style.display =""
        }
        else{
          document.getElementById("noresult").style.display ="none"
        
        }
      
    }

</script>